# Generated by Django 2.2.5 on 2019-09-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=60)),
                ('run_status', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=3)),
            ],
        ),
    ]
