# Generated by Django 2.2.5 on 2019-09-14 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pages',
            new_name='Page',
        ),
    ]
