# Generated by Django 2.2.5 on 2019-09-17 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentbot', '0004_page_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
