# Generated by Django 2.2.5 on 2019-09-17 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentbot', '0007_auto_20190917_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='account_id',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='page',
            name='latest_post_id',
            field=models.CharField(default='na', max_length=30),
        ),
        migrations.CreateModel(
            name='login_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
