# Generated by Django 2.2.5 on 2019-09-17 18:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commentbot', '0009_page_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_details',
            new_name='LoginDetails',
        ),
    ]
