# Generated by Django 2.2.5 on 2019-09-17 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentbot', '0010_auto_20190917_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
